version: '3'

tasks:
  install:
    cmds:
      - npm i -g prettier
      - npm i

  lint:
    cmds:
      - prettier --write .

  nextlint:
    cmds:
      - npx next lint

  dev:
    cmds:
      - npx next dev --port 4000

  build:
    cmds:
      - npx next build
